import React, { useState, useEffect, useCallback } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import {
  GraduationCap,
  LayoutDashboard,
  BookOpen,
  Trophy,
  Calendar,
  Layers,
  LineChart,
  Settings,
  Bell,
  Menu,
  X,
  LogOut,
  Wifi,
  WifiOff,
  RefreshCw,
  Mail,
  Send,
  Inbox
} from 'lucide-react';

import { useWebSocketManager } from './hooks/useWebSocketManager';
import { DashboardView } from './components/DashboardView';
import { NotesRepositoryView } from './components/NotesRepositoryView';
import { PracticeArenaView } from './components/PracticeArenaView';
import { PlannerView } from './components/PlannerView';
import { AnalyticsView } from './components/AnalyticsView';
import { AuthView } from './components/AuthView';
import { SettingsView } from './components/SettingsView';
import { Subject, Note, Flashcard, PracticeExam, LeaderboardEntry, PlannerTask, ActivityLog, Notification } from './types';

export default function App() {
  // Global auth states
  const [user, setUser] = useState<{ id: string; username: string; email: string } | null>(null);
  const [token, setToken] = useState<string | null>(null);
  const [authInitialized, setAuthInitialized] = useState(false);

  // Layout states
  const [currentView, setCurrentView] = useState<string>('dashboard');
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  // Notifications custom dropdown states
  const [showNotifDropdown, setShowNotifDropdown] = useState(false);
  const [notifTitle, setNotifTitle] = useState('');
  const [notifMessage, setNotifMessage] = useState('');
  const [isSendingNotif, setIsSendingNotif] = useState(false);
  const [sendSuccessMsg, setSendSuccessMsg] = useState('');

  // Core relational data states
  const [subjects, setSubjects] = useState<Subject[]>([]);
  const [notes, setNotes] = useState<Note[]>([]);
  const [flashcards, setFlashcards] = useState<Flashcard[]>([]);
  const [plannerTasks, setPlannerTasks] = useState<PlannerTask[]>([]);
  const [activityLogs, setActivityLogs] = useState<ActivityLog[]>([]);
  const [notifications, setNotifications] = useState<Notification[]>([]);
  const [leaderboard, setLeaderboard] = useState<LeaderboardEntry[]>([]);

  // Triggered helper data loaders
  const loadRelationalData = useCallback(async (authToken: string) => {
    try {
      const headers = { 'Authorization': `Bearer ${authToken}` };

      const [subjsRes, notesRes, cardsRes, tasksRes, logsRes, notifsRes, lboardRes] = await Promise.all([
        fetch('/api/subjects', { headers }).then(res => res.json()),
        fetch('/api/notes', { headers }).then(res => res.json()),
        fetch('/api/flashcards', { headers }).then(res => res.json()),
        fetch('/api/planner', { headers }).then(res => res.json()),
        fetch('/api/activity-logs', { headers }).then(res => res.json()),
        fetch('/api/notifications', { headers }).then(res => res.json()),
        fetch('/api/leaderboard').then(res => res.json())
      ]);

      if (Array.isArray(subjsRes)) setSubjects(subjsRes);
      if (Array.isArray(notesRes)) setNotes(notesRes);
      if (Array.isArray(cardsRes)) setFlashcards(cardsRes);
      if (Array.isArray(tasksRes)) setPlannerTasks(tasksRes);
      if (Array.isArray(logsRes)) setActivityLogs(logsRes);
      if (Array.isArray(notifsRes)) setNotifications(notifsRes);
      if (Array.isArray(lboardRes)) setLeaderboard(lboardRes);
    } catch (err) {
      console.error('Error fetching academic relational databases:', err);
    }
  }, []);

  // Web Sockets Event handlers wrapper
  const handleWebSocketEvent = useCallback((event: any) => {
    console.log('🔄 Live WebSocket update arrived on proxy:', event);
    
    // Dynamically patch React state lists upon server notifications to trigger animations
    switch (event.type) {
      case 'NOTIFICATION_BROADCAST':
        if (token) {
          fetch('/api/notifications', { headers: { 'Authorization': `Bearer ${token}` } })
            .then(res => res.json())
            .then(data => { if (Array.isArray(data)) setNotifications(data); });
        }
        break;
      case 'LEADERBOARD_REFRESH':
        fetch('/api/leaderboard')
          .then(res => res.json())
          .then(data => { if (Array.isArray(data)) setLeaderboard(data); });
        break;
      
      case 'SUBJECT_CREATED':
        setSubjects(prev => [event.payload, ...prev]);
        break;

      case 'NOTE_CREATED':
      case 'PDF_UPLOADED':
        setNotes(prev => [event.payload, ...prev]);
        // Also reload flashcards deck as they might be pre-generated by AI summary
        if (token) {
          fetch('/api/flashcards', { headers: { 'Authorization': `Bearer ${token}` } })
            .then(res => res.json())
            .then(data => { if (Array.isArray(data)) setFlashcards(data); });
        }
        break;

      case 'QUIZ_SUBMITTED':
        // Append activity logs
        fetch('/api/activity-logs', { headers: { 'Authorization': `Bearer ${token}` } })
          .then(res => res.json())
          .then(data => { if (Array.isArray(data)) setActivityLogs(data); });
        break;

      case 'PLANNER_UPDATED':
        setPlannerTasks(prev => {
          const index = prev.findIndex(t => t.id === event.payload.id);
          if (index !== -1) {
            const copy = [...prev];
            copy[index] = event.payload;
            return copy;
          }
          return [event.payload, ...prev];
        });
        break;

      default:
        break;
    }

    // Always fetch logs to refresh list feeds
    if (token) {
      fetch('/api/activity-logs', { headers: { 'Authorization': `Bearer ${token}` } })
        .then(res => res.json())
        .then(data => { if (Array.isArray(data)) setActivityLogs(data); });
    }
  }, [token]);

  // Hook ws manager to the app session
  const { status: socketStatus } = useWebSocketManager(token, handleWebSocketEvent);

  // Initialize session verification
  useEffect(() => {
    const checkSession = async () => {
      try {
        const resp = await fetch('/api/auth/session');
        if (resp.ok) {
          const data = await resp.json();
          if (data.user && data.token) {
            setUser(data.user);
            setToken(data.token);
            await loadRelationalData(data.token);
          }
        }
      } catch (err) {
        console.warn('Authentication checker idle.');
      } finally {
        setAuthInitialized(true);
      }
    };
    checkSession();
  }, [loadRelationalData]);

  // Auth Operations Handling Proxies
  const handleLogin = async (emailInput: string, passwordInput: string) => {
    const resp = await fetch('/api/auth/login', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email: emailInput, password: passwordInput })
    });

    if (!resp.ok) {
      const errData = await resp.json();
      throw new Error(errData.error || 'Check credentials.');
    }

    const data = await resp.json();
    setUser(data.user);
    setToken(data.token);
    await loadRelationalData(data.token);
  };

  const handleRegister = async (usernameInput: string, emailInput: string, passwordInput: string) => {
    const resp = await fetch('/api/auth/register', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ username: usernameInput, email: emailInput, password: passwordInput })
    });

    if (!resp.ok) {
      const errData = await resp.json();
      throw new Error(errData.error || 'Check validation formats.');
    }

    const data = await resp.json();
    setUser(data.user);
    setToken(data.token);
    await loadRelationalData(data.token);
  };

  const handleLogout = async () => {
    await fetch('/api/auth/logout', { method: 'POST' });
    setUser(null);
    setToken(null);
    setCurrentView('dashboard');
  };

  const handleMarkNotificationsRead = async () => {
    try {
      const resp = await fetch('/api/notifications/read', {
        method: 'POST',
        headers: { 'Authorization': `Bearer ${token}` }
      });
      if (resp.ok) {
        setNotifications(prev => prev.map(n => ({ ...n, read: true })));
      }
    } catch (err) {
      console.error('Failed reading notifications:', err);
    }
  };

  const handleSendNotification = async () => {
    if (!notifTitle.trim() || !notifMessage.trim()) return;
    setIsSendingNotif(true);
    setSendSuccessMsg('');
    try {
      const resp = await fetch('/api/notifications', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({
          title: notifTitle.trim(),
          message: notifMessage.trim()
        })
      });
      if (resp.ok) {
        const newNotif = await resp.json();
        setNotifications(prev => [...prev, newNotif]);
        setSendSuccessMsg(`Message dispatched! Copied to ${user?.email}`);
        setNotifTitle('');
        setNotifMessage('');
        setTimeout(() => setSendSuccessMsg(''), 6000);
      } else {
        const err = await resp.json();
        console.error('Service error:', err);
      }
    } catch (err) {
      console.error('Error dispatching message notification:', err);
    } finally {
      setIsSendingNotif(false);
    }
  };

  // Relational APIs operations proxies called by child modules
  const handleAddNewSubject = async (name: string, color: string) => {
    const resp = await fetch('/api/subjects', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${token}`
      },
      body: JSON.stringify({ name, color })
    });
    const sub = await resp.json();
    setSubjects(prev => [sub, ...prev]);
    return sub;
  };

  const handleAddNewNote = async (subjectId: string, title: string, content: string) => {
    const resp = await fetch('/api/notes', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${token}`
      },
      body: JSON.stringify({ subjectId, title, content })
    });
    if (!resp.ok) throw new Error('AI summarizing crashed.');
    const note = await resp.json();
    setNotes(prev => [note, ...prev]);
    return note;
  };

  const handleUploadPdfMaterial = async (fileName: string, base64: string, subjectId: string) => {
    const resp = await fetch('/api/notes/upload', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${token}`
      },
      body: JSON.stringify({ fileName, fileDataB64: base64, subjectId })
    });
    if (!resp.ok) {
      const errObj = await resp.json();
      throw new Error(errObj.error || 'Failed parsing PDF streams.');
    }
    const note = await resp.json();
    setNotes(prev => [note, ...prev]);
    return note;
  };

  const handleImportOnlineNote = async (
    title: string,
    subjectId: string,
    customSubjectName?: string,
    source?: string,
    pageid?: string | number,
    snippet?: string
  ) => {
    const resp = await fetch('/api/notes/import-online', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${token}`
      },
      body: JSON.stringify({ title, subjectId, customSubjectName, source, pageid, snippet })
    });
    if (!resp.ok) {
      const errObj = await resp.json();
      throw new Error(errObj.error || 'Failed importing online note.');
    }
    const note = await resp.json();
    
    // Refresh notes list dynamically
    setNotes(prev => [note, ...prev]);
    
    // Refresh subjects if a new custom one was added inline
    if (subjectId === 'custom' && token) {
      const subjsRes = await fetch('/api/subjects', {
        headers: { 'Authorization': `Bearer ${token}` }
      }).then(res => res.json());
      if (Array.isArray(subjsRes)) {
        setSubjects(subjsRes);
      }
    }
    return note;
  };

  const handleUpdateFlashcardMastery = async (cardId: string, mastery: 'unfamiliar' | 'review' | 'known') => {
    const resp = await fetch(`/api/flashcards/${cardId}`, {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${token}`
      },
      body: JSON.stringify({ mastery })
    });
    const card = await resp.json();
    setFlashcards(prev => prev.map(f => f.id === cardId ? card : f));
    return card;
  };

  const handleGeneratePracticeQuiz = async (noteId: string, difficulty: 'easy' | 'medium' | 'hard') => {
    const resp = await fetch(`/api/notes/${noteId}/generate-exam`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${token}`
      },
      body: JSON.stringify({ difficulty })
    });
    if (!resp.ok) throw new Error('AI Quiz generation failed.');
    return await resp.json();
  };

  const handleSubmitQuizResult = async (examId: string, score: number, totalQuestions: number, subjectId: string, title: string) => {
    const resp = await fetch('/api/quizzes/submit', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${token}`
      },
      body: JSON.stringify({ examId, score, totalQuestions, subjectId, title })
    });
    return await resp.json();
  };

  const handleAddTaskMilestone = async (title: string, subjectId: string, description: string, dueDate: string) => {
    const resp = await fetch('/api/planner', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${token}`
      },
      body: JSON.stringify({ title, subjectId, description, dueDate })
    });
    const task = await resp.json();
    setPlannerTasks(prev => [task, ...prev]);
    return task;
  };

  const handleUpdateTaskStatus = async (taskId: string, status: 'pending' | 'active' | 'completed') => {
    const resp = await fetch(`/api/planner/${taskId}`, {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${token}`
      },
      body: JSON.stringify({ status })
    });
    const task = await resp.json();
    setPlannerTasks(prev => prev.map(t => t.id === taskId ? task : t));
    return task;
  };

  const handleFetchAiRecommendations = async () => {
    const resp = await fetch('/api/analytics/ai-recommendations', {
      headers: { 'Authorization': `Bearer ${token}` }
    });
    return await resp.json();
  };

  const triggerLeaderboardRefresh = () => {
    fetch('/api/leaderboard')
      .then(res => res.json())
      .then(data => { if (Array.isArray(data)) setLeaderboard(data); });
  };

  // Navigations metadata
  const navItems = [
    { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard },
    { id: 'notes', label: 'Notes Repository', icon: BookOpen },
    { id: 'practice', label: 'Practice Arena', icon: Trophy },
    { id: 'planner', label: 'Milestone Planner', icon: Calendar },
    { id: 'analytics', label: 'Metric Analytics', icon: LineChart },
    { id: 'settings', label: 'Settings', icon: Settings }
  ];

  if (!authInitialized) {
    return (
      <div className="min-h-screen bg-[#0F1117] flex flex-col items-center justify-center text-gray-400 font-mono space-y-4">
        <RefreshCw className="w-8 h-8 animate-spin text-[#00C47A]" />
        <span>Booting Tutor AI Container...</span>
      </div>
    );
  }

  // Require Auth page if user is unauthenticated
  if (!user) {
    return (
      <AuthView onLogin={handleLogin} onRegister={handleRegister} />
    );
  }

  return (
    <div id="tutor-ai-app-root" className="min-screen bg-[#0F1117] text-[#F5F7FA] font-sans antialiased overflow-x-hidden flex flex-col min-h-screen justify-between select-none">
      
      {/* 1. Header Navigation Rails */}
      <header className="sticky top-0 bg-[#0F1117]/80 backdrop-blur-xl border-b border-white/5 py-4 px-8 flex items-center justify-between z-30">
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-xl bg-[#00C47A]/10 text-[#00C47A] shadow-[0_0_15px_rgba(0,196,122,0.15)]">
            <GraduationCap className="w-6 h-6" />
          </div>
          <div className="text-left leading-none">
            <span className="text-sm font-bold tracking-tight text-white block">Tutor AI</span>
            <span className="text-[10px] font-mono text-[#94A3B8] mt-1.5 block">Your Intelligent Academic Companion</span>
          </div>
        </div>

        {/* Global actions rail */}
        <div className="flex items-center gap-4">
          
          {/* Notifications count indicator */}
          <div className="relative">
            <button
              onClick={() => {
                setShowNotifDropdown(!showNotifDropdown);
                setSendSuccessMsg('');
              }}
              className={`relative cursor-pointer hover:text-white p-2 rounded-xl transition-colors flex items-center justify-center ${showNotifDropdown ? 'text-[#00C47A] bg-white/5' : 'text-[#94A3B8]'}`}
            >
              <Bell className="w-5 h-5" />
              {notifications.filter(n => !n.read).length > 0 && (
                <span className="absolute -top-0.5 -right-0.5 w-2.5 h-2.5 rounded-full bg-[#00C47A] shadow-[0_0_10px_rgba(0,196,122,0.5)]"></span>
              )}
            </button>

            {/* Dropdown menu */}
            <AnimatePresence>
              {showNotifDropdown && (
                <motion.div
                  initial={{ opacity: 0, y: 12, scale: 0.95 }}
                  animate={{ opacity: 1, y: 0, scale: 1 }}
                  exit={{ opacity: 0, y: 8, scale: 0.95 }}
                  transition={{ duration: 0.15 }}
                  className="absolute right-0 mt-3 w-80 sm:w-96 bg-[#181C25] rounded-2xl border border-white/5 shadow-[0_12px_40px_rgba(0,0,0,0.5)] p-4 z-50 space-y-4"
                >
                  <div className="flex items-center justify-between border-b border-white/5 pb-2.5">
                    <div className="flex items-center gap-1.5 text-white font-bold text-xs">
                      <Inbox className="w-4 h-4 text-indigo-400" />
                      <span>Mailbox Notifications ({notifications.length})</span>
                    </div>
                    <div className="flex gap-2 items-center">
                      {notifications.filter(n => !n.read).length > 0 && (
                        <button
                          onClick={handleMarkNotificationsRead}
                          className="text-[10px] text-[#00C47A] hover:underline cursor-pointer font-medium"
                        >
                          Mark all read
                        </button>
                      )}
                      <button
                        onClick={() => setShowNotifDropdown(false)}
                        className="text-[10px] text-gray-400 hover:text-white cursor-pointer px-1.5 py-0.5 rounded-md hover:bg-white/5 transition"
                      >
                        ✕
                      </button>
                    </div>
                  </div>

                  {/* List of Messages */}
                  <div className="max-h-52 overflow-y-auto space-y-2 pr-1 custom-scrollbar">
                    {notifications.length > 0 ? (
                      [...notifications].reverse().map((n) => (
                        <div
                          key={n.id}
                          className={`p-3 rounded-xl border text-left transition text-xs relative ${!n.read ? 'bg-indigo-600/5 border-indigo-500/20' : 'bg-[#0F1117]/60 border-white/5'}`}
                        >
                          {!n.read && (
                            <span className="absolute top-3 right-3 w-1.5 h-1.5 rounded-full bg-[#00C47A] animate-pulse"></span>
                          )}
                          <p className="font-bold text-gray-200">{n.title}</p>
                          <p className="text-[#94A3B8] text-[11px] mt-1 pr-4 leading-normal font-sans">{n.message}</p>
                          <span className="text-[9px] font-mono text-gray-500 block mt-2 text-right">
                            {new Date(n.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                          </span>
                        </div>
                      ))
                    ) : (
                      <div className="py-8 text-center text-gray-500 text-[11px] font-sans">
                        No notifications or mail messages inside your mailbox.
                      </div>
                    )}
                  </div>

                  {/* Compose section: "Make sure it sends a message" */}
                  <div className="border-t border-white/5 pt-3.5 space-y-2.5">
                    <span className="text-[10px] font-mono font-bold text-[#94A3B8] uppercase tracking-wider block text-left">
                      📨 Dispatch New Message / Notification
                    </span>
                    
                    {sendSuccessMsg && (
                      <p className="text-[10px] font-mono text-[#00C47A] bg-[#00C47A]/10 border border-[#00C47A]/20 p-2 rounded-xl animate-fadeIn text-left">
                        {sendSuccessMsg}
                      </p>
                    )}

                    <div className="space-y-2">
                      <input
                        type="text"
                        value={notifTitle}
                        onChange={(e) => setNotifTitle(e.target.value)}
                        placeholder="Subject (e.g. Exam Prep Reminder)"
                        className="w-full px-3 py-2 rounded-xl bg-[#0F1117] border border-white/5 text-xs text-white focus:outline-none focus:border-indigo-500 placeholder:text-gray-600 font-sans"
                      />
                      <textarea
                        value={notifMessage}
                        onChange={(e) => setNotifMessage(e.target.value)}
                        placeholder="Write message copy... (sends database log & socket broadcast to yourself)"
                        rows={2}
                        className="w-full px-3 py-2 rounded-xl bg-[#0F1117] border border-white/5 text-xs text-white focus:outline-none focus:border-indigo-500 placeholder:text-gray-600 font-sans resize-none"
                      />
                      <button
                        type="button"
                        onClick={handleSendNotification}
                        disabled={isSendingNotif || !notifTitle.trim() || !notifMessage.trim()}
                        className="w-full py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 text-white text-xs font-semibold transition-all flex items-center justify-center gap-1.5 cursor-pointer shadow-[0_4px_12px_rgba(99,102,241,0.25)] hover:shadow-[0_4px_16px_rgba(99,102,241,0.4)] disabled:shadow-none"
                      >
                        {isSendingNotif ? (
                          <>
                            <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                            Dispatching Message...
                          </>
                        ) : (
                          <>
                            <Send className="w-3.5 h-3.5" />
                            Send Message Notification
                          </>
                        )}
                      </button>
                    </div>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </div>

          <button
            onClick={() => setMobileMenuOpen(true)}
            className="p-1.5 rounded-lg text-[#94A3B8] hover:text-white md:hidden block focus:outline-none transition-colors"
          >
            <Menu className="w-6 h-6" />
          </button>
        </div>
      </header>

      {/* 2. Structured Layout Body container */}
      <div className="flex-1 flex max-w-7xl w-full mx-auto px-4 sm:px-6 py-6 gap-6 relative">
        
        {/* Desktop Left Sidebar layout */}
        <nav className="w-64 shrink-0 hidden md:block bg-[#181C25] rounded-2xl border border-white/5 p-4 space-y-8 min-h-[calc(100vh-140px)] shadow-[0_4px_24px_rgba(0,0,0,0.25)]">
          <div className="space-y-1.5">
            <span className="text-[10px] font-mono font-bold text-[#94A3B8] uppercase tracking-widest block px-3 mb-3">Navigation System</span>
            {navItems.map((item) => {
              const Icon = item.icon;
              const isActive = currentView === item.id;
              return (
                <button
                  key={item.id}
                  onClick={() => setCurrentView(item.id)}
                  className={`w-full text-left px-4 py-3 rounded-lg font-medium text-xs font-sans transition flex items-center space-x-3 hover:bg-white/5 hover:text-white focus:outline-none ${isActive ? 'bg-white/5 border-r-2 border-[#00C47A] text-[#00C47A] font-semibold' : 'text-[#94A3B8]'}`}
                >
                  <Icon className="w-4 h-4 shrink-0" />
                  <span>{item.label}</span>
                </button>
              );
            })}
          </div>

          <div className="pt-4 border-t border-white/5 space-y-4">
            <div className="px-3">
              <span className="text-[10px] font-mono block text-[#94A3B8]">Student Profile</span>
              <p className="text-xs font-bold text-white truncate mt-1">{user.username}</p>
              <p className="text-[10px] text-[#94A3B8] truncate mt-0.5">{user.email}</p>
            </div>

            <button
              onClick={handleLogout}
              className="w-full text-left px-3 py-2.5 rounded-xl text-rose-450 hover:bg-rose-500/5 text-xs text-rose-400 font-medium transition flex items-center gap-3"
            >
              <LogOut className="w-4 h-4" />
              <span>Sign Out</span>
            </button>
          </div>
        </nav>

        {/* Dynamic Display Panel */}
        <main className="flex-1 min-w-0">
          <AnimatePresence mode="wait">
            <motion.div
              key={currentView}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              transition={{ duration: 0.15 }}
              className="h-full"
            >
              {currentView === 'dashboard' && (
                <DashboardView
                  socketStatus={socketStatus}
                  subjects={subjects}
                  tasks={plannerTasks}
                  logs={activityLogs}
                  attempts={flashcards ? activityLogs.filter(l => l.activityType === 'quiz') : []}
                  onNavigate={setCurrentView}
                  user={user}
                />
              )}

              {currentView === 'notes' && (
                <NotesRepositoryView
                  subjects={subjects}
                  notes={notes}
                  onCreateSubject={handleAddNewSubject}
                  onCreateNote={handleAddNewNote}
                  onUploadPdf={handleUploadPdfMaterial}
                  onImportOnline={handleImportOnlineNote}
                  authToken={token || undefined}
                />
              )}

              {currentView === 'practice' && (
                <PracticeArenaView
                  notes={notes}
                  flashcards={flashcards}
                  leaderboard={leaderboard}
                  onUpdateFlashcardMastery={handleUpdateFlashcardMastery}
                  onGenerateQuiz={handleGeneratePracticeQuiz}
                  onSubmitQuizResult={handleSubmitQuizResult}
                  onRefreshLeaderboard={triggerLeaderboardRefresh}
                />
              )}

              {currentView === 'planner' && (
                <PlannerView
                  subjects={subjects}
                  tasks={plannerTasks}
                  onAddTask={handleAddTaskMilestone}
                  onUpdateTaskStatus={handleUpdateTaskStatus}
                />
              )}

              {currentView === 'analytics' && (
                <AnalyticsView onFetchRecommendations={handleFetchAiRecommendations} />
              )}

              {currentView === 'settings' && (
                <SettingsView user={user} onLogout={handleLogout} />
              )}
            </motion.div>
          </AnimatePresence>
        </main>

      </div>

      {/* 3. Mobile Slide drawer layout */}
      <AnimatePresence>
        {mobileMenuOpen && (
          <div className="fixed inset-0 z-40 md:hidden">
            
            {/* Backdrop filter */}
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 0.6 }}
              exit={{ opacity: 0 }}
              onClick={() => setMobileMenuOpen(false)}
              className="fixed inset-0 bg-[#0F1117] backdrop-blur-md"
            />

            {/* Slider menu content */}
            <motion.div
              initial={{ x: '100%' }}
              animate={{ x: 0 }}
              exit={{ x: '100%' }}
              transition={{ type: 'spring', bounce: 0, duration: 0.3 }}
              className="fixed top-0 right-0 bottom-0 w-72 bg-[#181C25] border-l border-white/5 p-6 flex flex-col justify-between shadow-2xl"
            >
              <div className="space-y-6 text-left">
                <div className="flex items-center justify-between border-b border-white/5 pb-3">
                  <span className="text-sm font-bold text-white">Tutor AI</span>
                  <button onClick={() => setMobileMenuOpen(false)} className="p-1 rounded bg-[#0F1117] text-gray-400">
                    <X className="w-5 h-5" />
                  </button>
                </div>

                <div className="space-y-2">
                  {navItems.map((item) => {
                    const Icon = item.icon;
                    const isActive = currentView === item.id;
                    return (
                      <button
                        key={item.id}
                        onClick={() => {
                          setCurrentView(item.id);
                          setMobileMenuOpen(false);
                        }}
                        className={`w-full text-left px-3.5 py-3 rounded-lg font-medium text-xs flex items-center space-x-3 transition hover:bg-white/5 hover:text-white ${isActive ? 'bg-white/5 border-r-2 border-[#00C47A] text-[#00C47A]' : 'text-[#94A3B8]'}`}
                      >
                        <Icon className="w-4 h-4" />
                        <span>{item.label}</span>
                      </button>
                    );
                  })}
                </div>
              </div>

              <div className="pt-4 border-t border-white/5 space-y-4 text-left">
                <div>
                  <span className="text-[10px] font-mono block text-[#94A3B8]">Student Profile</span>
                  <p className="text-xs font-bold text-white truncate mt-1">{user.username}</p>
                </div>
                <button
                  onClick={() => { handleLogout(); setMobileMenuOpen(false); }}
                  className="w-full text-left px-3 py-3 rounded-xl text-rose-450 hover:bg-rose-500/5 text-xs text-rose-400 font-bold transition flex items-center gap-3"
                >
                  <LogOut className="w-4 h-4" />
                  <span>Logout Session</span>
                </button>
              </div>

            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* Footer */}
      <footer className="py-4 border-t border-white/5 px-6 text-center text-[10px] font-mono text-[#94A3B8] flex flex-col sm:flex-row justify-between items-center max-w-7xl w-full mx-auto gap-2">
        <span>Tutor AI © 2026. Constructed in twilight minimalism.</span>
        <span className="flex items-center gap-2">
          Sync Service: <b>ws_express_native</b> 
          <span className="w-1.5 h-1.5 rounded-full bg-[#00C47A] shadow-[0_0_8px_rgba(0,196,122,0.8)] animate-pulse"></span>
        </span>
      </footer>

    </div>
  );
}
